# Étape 1 : Build
FROM node:18-slim AS build

WORKDIR /app
COPY app/frontend/package*.json ./
RUN npm install --no-audit --no-fund
COPY app/frontend/ ./
RUN npm run build

# Étape 2 : Serveur statique Nginx
FROM nginx:1.27-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]